/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gilesfinal;

/**
 *
 * @author Scott
 */
public class PlantingCalendar extends javax.swing.JPanel {

    /**
     * Creates new form PlantingCalendar
     */
    public PlantingCalendar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plantingCalendarLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        plantingCalendarTable = new javax.swing.JTable();

        plantingCalendarLabel.setText("Planting Calendar");

        plantingCalendarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Artichokes", "30 in", null, null, "2nd Half of Month", "All Month", null, null, null, null, null, null, null, null},
                {"Arugula", "6 in", null, "All Month", "All Month", null, null, null, null, "All Month", "All Month", "1st Half of Month", null, null},
                {"Beans, snap/bush", "2 in", "", null, "2nd Half of Month", null, null, null, null, "All Month", null, null, null, null},
                {"Basil", "5 in", null, null, null, null, "All Month", "All Month", "All Month", null, null, null, null, null},
                {"Beans, snap/pole", "6 in", null, null, null, "All Month", "All Month", "All Month", "All Month", null, "All Month", "1st Half of Month", null, null},
                {"Beets", "2 in", null, null, "All Month", null, null, null, "2nd Half of Month", "All Month", "1st Half of Month", null, null, null},
                {"Broccoli", "18 in", null, "2nd Half of Month", "All Month", null, null, null, null, "All Month", "1st Half of Month", null, null, null},
                {"Brussels sprouts", "14-18 in", null, null, null, null, null, null, "All Month", "All Month", null, null, null, null},
                {"Cabbage", "12 in", null, "All Month", "All Month", "1st Half of Month", null, null, "2nd Half of Month", "All Month", "1st Half of Month", null, null, null},
                {"Carrots", "2 in", null, "All Month", "All Month", null, null, "2nd Half of Month", "All Month", "All Month", "1st Half of Month", null, null, null},
                {"Cauliflower", "18 in", null, "2nd Half of Month", "All Month", "1st Half of Month", null, null, null, "All Month", "All Month", "1st Half of Month", null, null},
                {"Celery", "6-8 in", null, "2nd Half of Month", "All Month", null, null, "2nd Half of Month", "All Month", "1st Half of Month", null, null, null, null},
                {"Chard, swiss", "6 in", null, null, "All Month", "All Month", null, null, null, "All Month", "1st Half of Month", null, null, null},
                {"Cilantro", "2-4 in", null, "All Month", "All Month", null, null, null, null, null, "2nd Half of Month", "1st Half of Month", null, null},
                {"Collard greens", "18 in", null, "2nd Half of Month", "All Month", "All Month", "All Month", "All Month", "2nd Half of Month", "All Month", "1st Half of Month", null, null, null},
                {"Corn, sweet", "12 in", null, null, "2nd Half of Month", "All Month", "All Month", null, null, null, null, null, null, null},
                {"Cucumbers", "12 in", null, null, null, "2nd Half of Month", "All Month", "All Month", "All Month", "1st Half of Month", null, null, null, null},
                {"Dill", "2-4 in", null, null, "2nd Half of Month", null, null, null, null, "All Month", "1st Half of Month", null, null, null},
                {"Eggplant", "24 in", null, null, null, "2nd Half of Month", "All Month", "1st Half of Month", null, "All Month", null, null, null, null},
                {"Fennel", "6-12 in", null, null, "All Month", "All Month", null, null, "All Month", "All Month", null, null, null, null},
                {"Garlic", "4-6 in", null, null, null, null, null, null, null, null, "2nd Half of Month", "All Month Long", "All Month Long", null},
                {"Kale", "6 in", null, "2nd Half of Month", "All Month", "All Month", "All Month", "All Month", null, "All Month", "All Month", "1st Half of Month", null, null},
                {"Kohlrabi", "4 in", null, "2nd Half of Month", "All Month", "All Month", "All Month", "All Month", null, "All Month", "All Month", null, null, null},
                {"Leek", "4 in", null, "2nd Half of Month", "All Month", "All Month", "All Month", "All Month", null, null, null, null, null, null},
                {"Lettuce", "10 in", null, "All Month", "All Month", "All Month", null, null, null, "2nd Half of Month", "All Month", "1st Half of Month", null, null},
                {"Onions, bulb", "4 in", "All Month", "All Month", "All Month", null, null, null, null, "All Month", "All Month", "All Month Long", "All Month Long", "All Month Long"},
                {"Parsnips", "3-4 in", null, "2nd Half of Month", "All Month", null, null, null, null, "All Month", "All Month", "1st Half of Month", null, null},
                {"Peanuts", "6-8 in", null, null, null, null, "All Month", null, null, null, null, null, null, null},
                {"Peas, field", "4 in", "All Month", "All Month", "All Month", "1st Half of Month", "All Month", "All Month", null, "All Month", "All Month", "1st Half of Month", null, null},
                {"Peppers", "18 in", null, null, null, "2nd Half of Month", "All Month", "1st Half of Month", null, "1st Half of Month", null, null, null, null},
                {"Potatoes, irish", "10 in", null, "2nd Half of Month", "All Month", null, null, null, null, null, null, null, null, null},
                {"Potatoes, sweet", "10 in", null, null, null, null, "All Month", "All Month", "1st Half of Month", null, null, null, null, null},
                {"Pumpkin", "48 in", null, null, null, "2nd Half of Month", "All Month", "All Month", "1st Half of Month", null, null, null, null, null},
                {"Radish", "1 in", null, "All Month", "All Month", null, "All Month", "All Month", null, "All Month", "1st Half of Month", null, null, null},
                {"Rutabaga", "4 in", null, "All Month", "All Month", "1st Half of Month", null, null, "All Month", "All Month", "All Month", "1st Half of Month", null, null},
                {"Spinach", "6 in", null, "2nd Half of Month", "All Month", "All Month", "All Month", "All Month", "", "All Month", "All Month", "1st Half of Month", null, null},
                {"Squash, summer", "24 in", null, null, null, "All Month", "All Month", "All Month", "All Month", "1st Half of Month", null, null, null, null},
                {"Squash, winter", "36 in", null, null, null, "2nd Half of Month", "All Month", "All Month", "All Month", "1st Half of Month", null, null, null, null},
                {"Sunflower", "9-24 in", null, null, "2nd Half of Month", "All Month", "1st Half of Month", null, null, null, null, null, null, null},
                {"Tomatoes", "18 in", null, null, null, "2nd Half of Month", "All Month", "All Month", "1st Half of Month", "1st Half of Month", null, null, null, null},
                {"Turnips", "2 in", null, "All Month", "All Month", "All Month", "All Month", "All Month", null, "All Month", "1st Half of Month", null, null, null}
            },
            new String [] {
                "Plant", "Distance Between Plants", "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"
            }
        ));
        jScrollPane1.setViewportView(plantingCalendarTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(401, 401, 401)
                .addComponent(plantingCalendarLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1619, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plantingCalendarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel plantingCalendarLabel;
    private javax.swing.JTable plantingCalendarTable;
    // End of variables declaration//GEN-END:variables
}
