/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gilesfinal;

/**
 *
 * @author Scott
 */
public class PlantingCalendarForm extends javax.swing.JFrame {

    /**
     * Creates new form PlantingCalendarForm
     */
    public PlantingCalendarForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        plantingCalendarTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Main Page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        plantingCalendarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Artichokes", "30 in", null, null, "2nd Half of Month", "All Month", null, null, null, null, null, null, null, null},
                {"Arugula", "6 in", null, "All Month", "All Month", null, null, null, null, "All Month", "All Month", "1st Half of Month", null, null},
                {"Beans, snap/bush", "2 in", "", null, "2nd Half of Month", null, null, null, null, "All Month", null, null, null, null},
                {"Basil", "5 in", null, null, null, null, "All Month", "All Month", "All Month", null, null, null, null, null},
                {"Beans, snap/pole", "6 in", null, null, null, "All Month", "All Month", "All Month", "All Month", null, "All Month", "1st Half of Month", null, null},
                {"Beets", "2 in", null, null, "All Month", null, null, null, "2nd Half of Month", "All Month", "1st Half of Month", null, null, null},
                {"Broccoli", "18 in", null, "2nd Half of Month", "All Month", null, null, null, null, "All Month", "1st Half of Month", null, null, null},
                {"Brussels sprouts", "14-18 in", null, null, null, null, null, null, "All Month", "All Month", null, null, null, null},
                {"Cabbage", "12 in", null, "All Month", "All Month", "1st Half of Month", null, null, "2nd Half of Month", "All Month", "1st Half of Month", null, null, null},
                {"Carrots", "2 in", null, "All Month", "All Month", null, null, "2nd Half of Month", "All Month", "All Month", "1st Half of Month", null, null, null},
                {"Cauliflower", "18 in", null, "2nd Half of Month", "All Month", "1st Half of Month", null, null, null, "All Month", "All Month", "1st Half of Month", null, null},
                {"Celery", "6-8 in", null, "2nd Half of Month", "All Month", null, null, "2nd Half of Month", "All Month", "1st Half of Month", null, null, null, null},
                {"Chard, swiss", "6 in", null, null, "All Month", "All Month", null, null, null, "All Month", "1st Half of Month", null, null, null},
                {"Cilantro", "2-4 in", null, "All Month", "All Month", null, null, null, null, null, "2nd Half of Month", "1st Half of Month", null, null},
                {"Collard greens", "18 in", null, "2nd Half of Month", "All Month", "All Month", "All Month", "All Month", "2nd Half of Month", "All Month", "1st Half of Month", null, null, null},
                {"Corn, sweet", "12 in", null, null, "2nd Half of Month", "All Month", "All Month", null, null, null, null, null, null, null},
                {"Cucumbers", "12 in", null, null, null, "2nd Half of Month", "All Month", "All Month", "All Month", "1st Half of Month", null, null, null, null},
                {"Dill", "2-4 in", null, null, "2nd Half of Month", null, null, null, null, "All Month", "1st Half of Month", null, null, null},
                {"Eggplant", "24 in", null, null, null, "2nd Half of Month", "All Month", "1st Half of Month", null, "All Month", null, null, null, null},
                {"Fennel", "6-12 in", null, null, "All Month", "All Month", null, null, "All Month", "All Month", null, null, null, null},
                {"Garlic", "4-6 in", null, null, null, null, null, null, null, null, "2nd Half of Month", "All Month Long", "All Month Long", null},
                {"Kale", "6 in", null, "2nd Half of Month", "All Month", "All Month", "All Month", "All Month", null, "All Month", "All Month", "1st Half of Month", null, null},
                {"Kohlrabi", "4 in", null, "2nd Half of Month", "All Month", "All Month", "All Month", "All Month", null, "All Month", "All Month", null, null, null},
                {"Leek", "4 in", null, "2nd Half of Month", "All Month", "All Month", "All Month", "All Month", null, null, null, null, null, null},
                {"Lettuce", "10 in", null, "All Month", "All Month", "All Month", null, null, null, "2nd Half of Month", "All Month", "1st Half of Month", null, null},
                {"Onions, bulb", "4 in", "All Month", "All Month", "All Month", null, null, null, null, "All Month", "All Month", "All Month Long", "All Month Long", "All Month Long"},
                {"Parsnips", "3-4 in", null, "2nd Half of Month", "All Month", null, null, null, null, "All Month", "All Month", "1st Half of Month", null, null},
                {"Peanuts", "6-8 in", null, null, null, null, "All Month", null, null, null, null, null, null, null},
                {"Peas, field", "4 in", "All Month", "All Month", "All Month", "1st Half of Month", "All Month", "All Month", null, "All Month", "All Month", "1st Half of Month", null, null},
                {"Peppers", "18 in", null, null, null, "2nd Half of Month", "All Month", "1st Half of Month", null, "1st Half of Month", null, null, null, null},
                {"Potatoes, irish", "10 in", null, "2nd Half of Month", "All Month", null, null, null, null, null, null, null, null, null},
                {"Potatoes, sweet", "10 in", null, null, null, null, "All Month", "All Month", "1st Half of Month", null, null, null, null, null},
                {"Pumpkin", "48 in", null, null, null, "2nd Half of Month", "All Month", "All Month", "1st Half of Month", null, null, null, null, null},
                {"Radish", "1 in", null, "All Month", "All Month", null, "All Month", "All Month", null, "All Month", "1st Half of Month", null, null, null},
                {"Rutabaga", "4 in", null, "All Month", "All Month", "1st Half of Month", null, null, "All Month", "All Month", "All Month", "1st Half of Month", null, null},
                {"Spinach", "6 in", null, "2nd Half of Month", "All Month", "All Month", "All Month", "All Month", "", "All Month", "All Month", "1st Half of Month", null, null},
                {"Squash, summer", "24 in", null, null, null, "All Month", "All Month", "All Month", "All Month", "1st Half of Month", null, null, null, null},
                {"Squash, winter", "36 in", null, null, null, "2nd Half of Month", "All Month", "All Month", "All Month", "1st Half of Month", null, null, null, null},
                {"Sunflower", "9-24 in", null, null, "2nd Half of Month", "All Month", "1st Half of Month", null, null, null, null, null, null, null},
                {"Tomatoes", "18 in", null, null, null, "2nd Half of Month", "All Month", "All Month", "1st Half of Month", "1st Half of Month", null, null, null, null},
                {"Turnips", "2 in", null, "All Month", "All Month", "All Month", "All Month", "All Month", null, "All Month", "1st Half of Month", null, null, null}
            },
            new String [] {
                "Plant", "Distance Between Plants", "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"
            }
        ));
        jScrollPane2.setViewportView(plantingCalendarTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(434, 434, 434)
                .addComponent(jButton1)
                .addContainerGap(503, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(689, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        LandingPage landingPage = new LandingPage();
        landingPage.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlantingCalendarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlantingCalendarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlantingCalendarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlantingCalendarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlantingCalendarForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable plantingCalendarTable;
    // End of variables declaration//GEN-END:variables
}
